name: ActionWorkFlowCommandTest
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Test debug 
      run: echo "::debug::This is a debug message"

    - name: Test warning
      run: echo "::warning file=somefile.cs,line=1,col=5::Achtung, test failed"

    - name: Test error
      run: echo "::error file=someotherfile.cs,line=16,col=8::Achtung, test kaput"

    - name: Test warning multiline
      run: echo "::warning file=somefile.cs,line=1,col=5::Achtung, test failed\njust a warning"
