name: Release
on:
  release:
    types: [published]
#  push:           #TEST emulate release on push on master
#    branches:     #TEST emulate release on push on master
#      - master    #TEST emulate release on push on master

# To publish a release; tag "v" + "Version(Mandatory)" + "-" + "VersionSuffix(Optional)"
# Tag: v5.0.0-preview1   or v5.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
      CONFIGURATION: Release
      NUPKGPATH: packages

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      name: Setup .NET '3.1.x'
      with: 
        dotnet-version: '3.1.x'
        source-url: https://nuget.pkg.github.com/dogguts/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/setup-dotnet@v1
      name: Setup .NET 5
      with:
        dotnet-version: '5.0.x'
        source-url: https://nuget.pkg.github.com/dogguts/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: actions/setup-dotnet@v1
      name: Setup .NET 6.0
      with:
        dotnet-version: '6.0.x'
        source-url: https://nuget.pkg.github.com/dogguts/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Set release version
      run: | 
        REL_GITHUB_REF=$GITHUB_REF
        
        #REL_GITHUB_REF="refs/tags/v1.1.0-preview2$GITHUB_RUN_NUMBER"   #TEST emulate release on push on master
 
        REL_VERSION="${REL_GITHUB_REF/refs\/tags\/v/}"  
        REL_VERSION_ONLY=$( echo "$REL_VERSION" | cut -d\- -f1) 

        echo 'REL_VERSION='$REL_VERSION | tee -a $GITHUB_ENV
        echo 'REL_VERSION_ONLY='$REL_VERSION_ONLY | tee -a $GITHUB_ENV
        
        echo "nuget sources"
        dotnet nuget list source
         
    - name: Build
      run: |
        dotnet build aeon.sln --configuration Release

    - name: Run Tests
      run: |
        dotnet test tests/Repository.Test.Integration --logger "github;name=test-report;GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" 

    - name: Pack
      run: |
        dotnet pack src/Aeon.Core.Repository/ --configuration $CONFIGURATION -p:Version=${{env.REL_VERSION}} -p:RepositoryCommit=$GITHUB_SHA -p:AssemblyVersion=${{env.REL_VERSION_ONLY}}.0 -p:FileVersion=${{env.REL_VERSION_ONLY}}.0 -o $NUPKGPATH
        dotnet pack src/Aeon.Core.Repository.Extensions/ --configuration $CONFIGURATION -p:Version=${{env.REL_VERSION}} -p:RepositoryCommit=$GITHUB_SHA -p:AssemblyVersion=${{env.REL_VERSION_ONLY}}.0 -p:FileVersion=${{env.REL_VERSION_ONLY}}.0 -o $NUPKGPATH

    - name: List packages
      run: |
        pwd
        ls $NUPKGPATH 

# temp disabld
#    - name: Publish packages to NuGet.org
#      run: |
#        dotnet nuget push $NUPKGPATH'/*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_KEY}}
        
